/* USED ORACLE DATABASE */

CREATE TABLE GRADE_DESC 
(SID INTEGER NOT NULL, 
 CLASSNAME VARCHAR(6) NOT NULL, 
 GRADE CHAR(1) NOT NULL);
 
 INSERT INTO GRADE_DESC VALUES(123, 'ART123', 'A');
 INSERT INTO GRADE_DESC VALUES(123, 'BUS456', 'B');
 INSERT INTO GRADE_DESC VALUES(666, 'REL100', 'D');
 INSERT INTO GRADE_DESC VALUES(666, 'ECO966', 'A');
 INSERT INTO GRADE_DESC VALUES(666, 'BUS456', 'B');	
 INSERT INTO GRADE_DESC VALUES(345, 'BUS456', 'A');
 INSERT INTO GRADE_DESC VALUES(345, 'ECO966', 'F');
 
 

SELECT CLASSNAME, COUNT(CLASSNAME) AS TOTAL 
FROM GRADE_DESC
GROUP BY CLASSNAME
ORDER BY TOTAL;