/* ORACLE DATABASE */
CREATE TABLE SPAM
(NAME VARCHAR(20),
ADDRESS CHAR(1),
ID INTEGER,
SAMEFAM INTEGER);

INSERT INTO SPAM VALUES('ALICE', 'A', 10, NULL);
INSERT INTO SPAM VALUES('BOB', 'B', 15, NULL);
INSERT INTO SPAM VALUES('CARMEN', 'C', 22, NULL);
INSERT INTO SPAM VALUES('DIEGO', 'A', 9, 10);
INSERT INTO SPAM VALUES('ELLA', 'B', 3, 15);
INSERT INTO SPAM VALUES('FARKHAD', 'D', 11, NULL);


DELETE FROM SPAM 
WHERE ID IN (SELECT S.SAMEFAM FROM SPAM S WHERE S.SAMEFAM IS NOT NULL);

SELECT * FROM SPAM;